'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import LivepeerClient from '../client'
import { LivepeerConfig } from '@livepeer/react'
import '@rainbow-me/rainbowkit/styles.css';
import { darkTheme, getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import { mainnet, polygon, optimism, arbitrum, filecoinCalibration } from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, polygon, optimism, arbitrum, filecoinCalibration],
  [
    alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY }),
    publicProvider()
  ]
);

const { connectors } = getDefaultWallets({
  appName: 'demo.vault',
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  chains
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
  webSocketPublicClient
})

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
      </head>
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chains}>
            <LivepeerConfig client={LivepeerClient}>
              {children}
            </LivepeerConfig>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  )
}
