'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import LivepeerClient from '../client'
import { LivepeerConfig } from '@livepeer/react'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
      </head>
      <body className={inter.className}>
        <LivepeerConfig client={LivepeerClient}>
          {children}
        </LivepeerConfig>
      </body>
    </html>
  )
}
